travis:
  secure:
    BINSTAR_TOKEN: LgzysiPgYzeewzcKOzfjxSwSr+is9qUb8ImSIjj0BX7Dh+x3O02l7yl/SqJ4oSHDqso+xlR7j+daQl187ZRLT8ODU9rpjnbJ90UBlvkLF1wcUGvw+B4u5H+vjhUERLHwoH1rH0UztVBYjT2jDkADIRZ6VrurZadvPkvKtHp8old3HoU5pdo2M/felrG4/LO/7/jezZP7sci4aKMuQ3q+umjPStbYMPA38ouTgy5jdXj53Y23cHfuFfC18KYCP0Q2xisAtNQRcVHI9mc+wKjMYEio9uNYEIK8PEMpQGWTsJofqTTOHXIIcblxsmPL/4ptiyPrf9lEezMb3pbY31lT4qU3PSznLvZIyUSQkisHdv6zDaiLSz2D6aROceWLlC9DywYwpHujBRA2AN8P7aH4PpB+/y+BQSepgWiEb3/M/7m3rKYDCpK9ffKBsxkBdTDat/mo9rhMXiB030uDqUTHlZLDTKSKyDDZ59WyYAGtB3ESwIap6uaNxHBwMfsLDZ8hDkwGXvPRj4mHGBPVjZi3D3bUzmUPARYJEhX0hWMOTHZehjdg3pppcJN/l/lrGyZrQORSEhakjAOogYc+7XC//dMcjilYuya9exbXN8LC+6ZA9r5gREsRZ4w+T4jsJKo3UFqLoH0y/ec0ttdcwxOZC5gWkVIk+EyQtyq+C7mXugw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
